#!/usr/bin/env node

var fs = require('fs');
var argv = require('optimist').argv;
var forrer = require('./src/forrer');

if (argv.help) {

    // Help

    console.log([
        'forrer: HELP',
        "Usage: forrer [-o 'output-file'] 'input-file'",
        '       or pipe mode',
        '',
        "    If `-o' parameter not specified output will put in standard output."
    ].join('\n'));

} else if (argv._.length) {

    // Command line arguments mode

    var code = fs.readFileSync(argv._[0]).toString();

    var newCode = forrer(code);

    if (argv.o) {
        fs.writeFileSync(argv.o, newCode);
    } else {
        process.stdout.write(newCode);
    }
} else {

    // Pipe mode

    var codeChunks = [];

    process.stdin.on('readable', function() {
        var chunk = process.stdin.read();
        if (chunk !== null) {
            codeChunks.push(chunk);
        }
    });

    process.stdin.on('end', function() {
        var code = codeChunks.join('');
        process.stdout.write(forrer(code));

    });
}
